version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    depends_on:
      - api
    volumes:
      - "./services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - metrics:/prometheus
    ports:
      - ${PORT_METRICS:-9090}:9090
  grafana:
    image: grafana/grafana:7.1.0
    ports:
      - ${PORT_GRAFANA:-9091}:3000
    volumes:
      - graphs:/var/lib/grafana

volumes:
  metrics:
  graphs:
