version: "3.7"

services:
  db:
    image: neo4j:4.1
    restart: unless-stopped
    ports:
      - ${NEO4J_PORT:-7687}:7687
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4JLABS_PLUGINS=["apoc"]
    volumes:
      - "./data:/data:Z"
      - "./logs:/logs:Z"
  api:
    build:
      context: "./services/api/"
      args:
        VERSION: ${DATACAT_VERSION}
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - SPRING_APPLICATION_JSON=${DATACAT_APPLICATION_JSON}
      - spring.data.neo4j.uri=bolt://db:7687
      - spring.data.neo4j.username=${NEO4J_USER}
      - spring.data.neo4j.password=${NEO4J_PASSWORD}
  web:
    build:
      context: "./services/proxy/"
      args:
        VERSION: ${DATACAT_EDITOR_VERSION}
    depends_on:
      - api
    restart: unless-stopped
    ports:
      - ${DATACAT_PORT:-3000}:80
