version: '3.7'

services:
  db:
    image: neo4j:4.1
    restart: always
    ports:
    - 7687:7687
    environment:
    - NEO4J_AUTH=${NEO4J_AUTH}
    - NEO4JLABS_PLUGINS=["apoc"]
    volumes:
    - "./data:/data:Z"
    - "./logs:/logs:Z"
  api:
    build:
      context: "./services/api/"
      args:
        VERSION: ${DATACAT_VERSION}
    depends_on:
      - db
    restart: always
    environment:
      - spring.data.neo4j.uri=bolt://db:7687
      - spring.data.neo4j.username=${NEO4J_USERNAME}
      - spring.data.neo4j.password=${NEO4J_PASSWORD}
  explorer:
    image: bentrm/datacat:${DATACAT_EXPLORER_VERSION:-latest-explorer}
    depends_on:
      - api
    restart: always
  proxy:
    build: "./services/proxy/"
    depends_on:
      - api
      - explorer
    ports:
      - ${PORT:-3000}:80
